### ISSUE TITLE
Glitch while rendering custom images

### ISSUE THREAD

**Issue by buger** [jacomyal/sigma.js#1383]
## Guidelines

I cloned https://github.com/jacomyal/sigma.js/tree/main/demo and replaced it with my own data and new icons. 
Icons are in PNG format. Have not performed anything else custom. 

When I reload the page, icons are glitching on load, see the video:
https://www.loom.com/share/26d30cfbcc96459fabf3f32941ad0f7f

Any ideas? Happy to provide more debugging.

Issue visible for both Chrome and Safari

**Comment by buger** [comment]
Actually I realized that exactly the same issue visible on official demo too https://www.sigmajs.org/demo/index.html
Just reload it a few times and forcing not using a cache. Sometimes it happens too fast, but if you look closely you will see that it spinning though the various icons, before it ends up with final icon.

**Comment by buger** [comment]
Seems like this issue was fixed in later versions of sigma. I updated it to latest version, and seems to be working!

**Comment by jacomyal** [comment]
OK, I couldn't reproduce it with the https://www.sigmajs.org/demo/index.html - but I've had recently multiple feedbacks on issues with the texture generation in this renderer indeed... You still see this issue with the online demo?

**Comment by buger** [comment]
On demo it is very hard to replicate because icons are svg, and there are a few of them. In my case it was a lot of PNG's. 
Anyway I'm closing it because with newer Sigma version issue got fixed.
